version: '3'

services:
  servidor:
    build: 
      context: ./servidor
    container_name: "servidor"
    volumes: 
      - ./servidor:/app

  cliente:
    build: 
      context: ./cliente
    depends_on:
      - servidor
    container_name: "cliente"
    volumes: 
      - ./cliente:/app
